### ISSUE TITLE
Regex escape sequences lead to incorrect generated code

### ISSUE THREAD

**Issue by asm0dey** [vendelieu/telegram-bot#106] opened 2024-03-07 09:34 UTC
**Describe the bug**
If I use `\s` in command like `@RegexCommandHandler("/go\\s")` I get a compilation error

**Expected behavior**
The string remains as is in the generated code and does not lead to a compilation error

I assume that the issue is code is generated somehow manually instead of using specialized libraries like KotlinPoet

**Comment by vendelieu** [comment] 2024-03-07 21:28
Thanks for report.
The problem was incorrect string inlining. 
Fixed in 5.0.2, If the problem is still present please let me know.

**Closed** 2024-03-09 13:08 UTC
Labels: bug
